# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Card.create(name: 'Стесняшка', photo: 'Таракашки/1.Стесняшка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Работяжка', photo: 'Таракашки/2.Работяжка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Обжорка', photo: 'Таракашки/3.Обжорка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Ленус', photo: 'Таракашки/4.Ленус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Манипуляш', photo: 'Таракашки/5.Манипуляш.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Великолепус', photo: 'Таракашки/6.Великолепиус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Обижака', photo: 'Таракашки/7.Обижака.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Депрессун', photo: 'Таракашки/8.Депрессун.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Агрессиус', photo: 'Таракашки/9.Агрессиус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Хорош Прехорош', photo: 'Таракашки/10.Хорош Прехорош.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Бояшка', photo: 'Таракашки/11.Бояшка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Капризка', photo: 'Таракашки/12.Капризка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Вредина', photo: 'Таракашки/13.Вредина.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Виноватик', photo: 'Таракашки/14.Виноватик.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Инфантик', photo: 'Таракашки/15.Инфантик.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Всем Угодий', photo: 'Таракашки/16.Всем Угодий.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Себя Нелюбяш', photo: 'Таракашки/17.Себя Нелюбяш.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Жертвыч', photo: 'Таракашки/18.Жертвыч.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Ипохондрыч', photo: 'Таракашки/19.Ипохондрыч.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Соревновашка', photo: 'Таракашки/20.Соревновашка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Рискун', photo: 'Таракашки/21.Рискун.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Подозревашка', photo: 'Таракашки/22.Подозревашка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Соблазняшка', photo: 'Таракашки/23.Соблазняшка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Всезнайка', photo: 'Таракашки/24.Всезнайка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Бедняшка', photo: 'Таракашки/25.Бедняжка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Ловелас', photo: 'Таракашки/26.Ловелас.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Невменяшка', photo: 'Таракашки/27.Невменяшка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Притворяшка', photo: 'Таракашки/28.Притворяшка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Тревожинка', photo: 'Таракашки/29.Тревожинка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Недоверяшка', photo: 'Таракашки/30.Недоверяшка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Зацикленыш', photo: 'Таракашки/31.Зациклёныш.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Спорыч', photo: 'Таракашки/32.Спорыч.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Сомнениус', photo: 'Таракашки/33.Сомнениус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Молчун', photo: 'Таракашки/34.Молчун.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Нехочуха', photo: 'Таракашки/35.Нехочуха.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Мстяка', photo: 'Таракашки/36.Мстяка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Крутяшка', photo: 'Таракашки/37.Крутяшка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Чего-то Ждун', photo: 'Таракашки/38.Чего-то Ждун.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Кузькина мать', photo: 'Таракашки/39.Кузькина мать.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Контролюс', photo: 'Таракашки/40.Контролюс.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Самонаказун', photo: 'Таракашки/41.Самонаказун.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Принцесса', photo: 'Таракашки/42.Принцесса.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Поучайка', photo: 'Таракашки/43.Поучайка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Критиканус', photo: 'Таракашки/44.Критиканус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Копилкин', photo: 'Таракашки/45.Копилкин.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Мозговыносяшки', photo: 'Таракашки/46.Мозговыносяшки.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Саботажка', photo: 'Таракашки/47.Саботажка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Авоська', photo: 'Таракашки/48.Авоська.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Мистер Прокрастинати', photo: 'Таракашки/49.Мистер Прокрастинати.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Дурашка', photo: 'Таракашки/50.Дурашка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Самообманус', photo: 'Таракашки/51.Самообманус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Капитан Справедливость', photo: 'Таракашки/52.Капитан Справедливость.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Самокопай', photo: 'Таракашки/53.Самокопай.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Ярлыкаш', photo: 'Таракашки/54.Ярлыкаш.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Одинокушка', photo: 'Таракашки/55.Одинокушка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Недообнимашка', photo: 'Таракашки/56.Недообнимашка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Тормозяш', photo: 'Таракашки/57.Тормозяш.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Интровертус', photo: 'Таракашки/58.Интровертус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Забываш', photo: 'Таракашки/59.Забываш.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Перфектус', photo: 'Таракашки/60.Перфектус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Навязович', photo: 'Таракашки/61.Навязович.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Возмущун', photo: 'Таракашки/62.Возмущун.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Честноглазик Хитропопик', photo: 'Таракашки/63.Честноглазик Хитропопик.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Тираниус', photo: 'Таракашки/64.Тираниус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Немогун', photo: 'Таракашки/65.Немогун.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Неудачник', photo: 'Таракашки/66.Неудачкин.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Карьерыч', photo: 'Таракашки/67.Карьерыч.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Равнодушкин', photo: 'Таракашки/68.Равнодушкин.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Измухи Слон', photo: 'Таракашки/69.Измухи Слон.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Неуспевашка', photo: 'Таракашки/70.Неуспевашка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Мнениус Зависимус', photo: 'Таракашки/71.Мнениус Зависимус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Несмеяна', photo: 'Таракашки/72.Несмеяна.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Установыч', photo: 'Таракашки/73.Установыч.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Плакса', photo: 'Таракашки/74.Плакса.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Ворчун', photo: 'Таракашки/75.Ворчун.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Ревнивус', photo: 'Таракашки/76.Ревнивус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Психосаматикус', photo: 'Таракашки/77.Психосоматикус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Нострадамус', photo: 'Таракашки/78.Нострадамус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Эгоистус', photo: 'Таракашки/79.Эгоистус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Песимистушка', photo: 'Таракашки/80.Пессимистушка.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Позитивыч', photo: 'Таракашки/81.Позитивыч.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Легкомыслиш', photo: 'Таракашки/82.Легкомыслиш.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Сплетникус', photo: 'Таракашки/83.Сплетникус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Таксебе Родитель', photo: 'Таракашки/84.Таксебе Родитель.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Упрямикус', photo: 'Таракашки/85. Упрямикус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Идиализириус', photo: 'Таракашки/86.Идеализириус.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Фома Неверующий', photo: 'Таракашки/87.Фома Неверующий.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
Card.create(name: 'Плохиш', photo: 'Таракашки/88.Плохиш.jpg', shirt: 'Таракашки/Рубашка.jpg', deck_name: 'Таракашки')
