# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Card.create(name: 'Стесняшка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Работяжка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Обжорка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Ленус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Манипуляш', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Великолепус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Обижака', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Депрессун', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Агрессиус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Хорош Прехорош', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Бояшка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Капризка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Вредина', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Виноватик', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Инфантик', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Всем Угодий', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Себя Нелюбяш', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Жертвыч', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Ипохондрыч', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Соревновашка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Рискун', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Подозревашка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Соблазняшка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Всезнайка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Бедняшка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Ловелас', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Невменяшка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Притворяшка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Тревожинка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Недоверяшка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Зацикленыш', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Спорыч', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Сомнениус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Молчун', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Нехочуха', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Мстяка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Крутяшка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Чего-то Ждун', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Кузькина мать', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Контролюс', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Самонаказун', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Принцесса', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Поучайка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Критиканус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Копилкин', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Мозговыносяшки', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Саботажка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Авоська', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Мистер Прокрастинати', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Дурашка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Самообманус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Капитан Справедливость', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Самокопай', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Ярлыкаш', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Одинокушка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Недообнимашка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Тормозяш', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Интровертус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Забываш', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Перфектус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Навязович', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Возмущун', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Честноглазик Хитропопик', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Тираниус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Немогун', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Неудачник', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Карьерыч', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Равнодушкин', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Измухи Слон', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Неуспевашка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Мнениус Зависимус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Несмеяна', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Установыч', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Плакса', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Ворчун', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Ревнивус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Психосаматикус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Нострадамус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Эгоистус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Песимистушка', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Позитивыч', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Легкомыслиш', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Сплетникус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Таксебе Родитель', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Упрямикус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Идиализириус', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Фома Неверующий', photo: '', shirt: '', deck_name: 'Таракашки')
Card.create(name: 'Плохищ', photo: '', shirt: '', deck_name: 'Таракашки')
